### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by CristieW**

### CODE REVIEW

**Review by Lprods01 — CHANGES_REQUESTED** [review]
This code so far looks great. I only have one comment, this code accomplishes the first task, finding the total resale value, but it does not complete the second which is finding the total resale value for each item type. Could you update the file to complete this second task?

**Comment by CristieW** [comment]
This has been completed. Could you send me instructions on how to update
the branch in GitHub?
sorry for the late email, I couldn't sleep until this was completed.

**Review by Lprods01 — APPROVED** [review]
This looks great!

**Comment by Lprods01** [comment]
Closing PR, interview is complete

**Pull request closed without merging**
